# Generated by Django 5.0.1 on 2024-01-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField(max_length=30, verbose_name='Название таблицы')),
                ('table', models.TextField(verbose_name='Таблица')),
                ('graph_skills', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График по скиллам')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_salary_level', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График уровень зарплат по годам')),
                ('graph_num_vacancy', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График количество вакансий по годам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_salary_level_by_city', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График уровень зарплат по городам')),
                ('graph_vacancy_fraction_by_city', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График доля вакансий по городам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('photo', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
    ]
